# Generated by Django 4.1.1 on 2022-09-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schedule',
            field=models.DateField(blank=True, null=True),
        ),
    ]
